
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label1;
	private global::Gtk.Entry csProjTextBox;
	private global::Gtk.Button compileButton;
	private global::Gtk.ComboBox recentCSProjs;
	private global::Gtk.Label label3;
	private global::Gtk.ComboBox compileTypesComboBox;
	private global::Gtk.CheckButton compileMetroShadersCheckBox;
	private global::Gtk.ComboBox recentShaderOutputs;
	private global::Gtk.Entry shaderDirTextBox;
	private global::Gtk.Label label2;
	private global::Gtk.CheckButton compileSilverlightShaders;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Shader Compiler");
		this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("CS Proj:");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 10;
		w1.Y = 48;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.csProjTextBox = new global::Gtk.Entry ();
		this.csProjTextBox.WidthRequest = 500;
		this.csProjTextBox.CanFocus = true;
		this.csProjTextBox.Name = "csProjTextBox";
		this.csProjTextBox.Text = global::Mono.Unix.Catalog.GetString ("Enter CS Proj file name here...");
		this.csProjTextBox.IsEditable = true;
		this.csProjTextBox.InvisibleChar = '●';
		this.fixed1.Add (this.csProjTextBox);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.csProjTextBox]));
		w2.X = 60;
		w2.Y = 44;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.compileButton = new global::Gtk.Button ();
		this.compileButton.CanFocus = true;
		this.compileButton.Name = "compileButton";
		this.compileButton.UseUnderline = true;
		this.compileButton.Label = global::Mono.Unix.Catalog.GetString ("Compile");
		this.fixed1.Add (this.compileButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.compileButton]));
		w3.X = 575;
		w3.Y = 226;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.recentCSProjs = global::Gtk.ComboBox.NewText ();
		this.recentCSProjs.Name = "recentCSProjs";
		this.fixed1.Add (this.recentCSProjs);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.recentCSProjs]));
		w4.X = 529;
		w4.Y = 16;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Compile Types:");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w5.X = 20;
		w5.Y = 225;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.compileTypesComboBox = global::Gtk.ComboBox.NewText ();
		this.compileTypesComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("All"));
		this.compileTypesComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("D3D11"));
		this.compileTypesComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("D3D9"));
		this.compileTypesComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("XNA"));
		this.compileTypesComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Silverlight"));
		this.compileTypesComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("GL2"));
		this.compileTypesComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("GL3"));
		this.compileTypesComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("GLES2"));
		this.compileTypesComboBox.Name = "compileTypesComboBox";
		this.compileTypesComboBox.Active = 0;
		this.fixed1.Add (this.compileTypesComboBox);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.compileTypesComboBox]));
		w6.X = 114;
		w6.Y = 223;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.compileMetroShadersCheckBox = new global::Gtk.CheckButton ();
		this.compileMetroShadersCheckBox.CanFocus = true;
		this.compileMetroShadersCheckBox.Name = "compileMetroShadersCheckBox";
		this.compileMetroShadersCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Compile Metro Shaders");
		this.compileMetroShadersCheckBox.Active = true;
		this.compileMetroShadersCheckBox.DrawIndicator = true;
		this.compileMetroShadersCheckBox.UseUnderline = true;
		this.fixed1.Add (this.compileMetroShadersCheckBox);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.compileMetroShadersCheckBox]));
		w7.X = 223;
		w7.Y = 223;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.recentShaderOutputs = global::Gtk.ComboBox.NewText ();
		this.recentShaderOutputs.Name = "recentShaderOutputs";
		this.fixed1.Add (this.recentShaderOutputs);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.recentShaderOutputs]));
		w8.X = 535;
		w8.Y = 93;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.shaderDirTextBox = new global::Gtk.Entry ();
		this.shaderDirTextBox.WidthRequest = 500;
		this.shaderDirTextBox.CanFocus = true;
		this.shaderDirTextBox.Name = "shaderDirTextBox";
		this.shaderDirTextBox.Text = global::Mono.Unix.Catalog.GetString ("Enter Shader Compiled output dir here...");
		this.shaderDirTextBox.IsEditable = true;
		this.shaderDirTextBox.InvisibleChar = '●';
		this.fixed1.Add (this.shaderDirTextBox);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.shaderDirTextBox]));
		w9.X = 74;
		w9.Y = 124;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Shader Dir:");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w10.X = 10;
		w10.Y = 126;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.compileSilverlightShaders = new global::Gtk.CheckButton ();
		this.compileSilverlightShaders.CanFocus = true;
		this.compileSilverlightShaders.Name = "compileSilverlightShaders";
		this.compileSilverlightShaders.Label = global::Mono.Unix.Catalog.GetString ("Compile Silverlight Shaders");
		this.compileSilverlightShaders.Active = true;
		this.compileSilverlightShaders.DrawIndicator = true;
		this.compileSilverlightShaders.UseUnderline = true;
		this.fixed1.Add (this.compileSilverlightShaders);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.compileSilverlightShaders]));
		w11.X = 223;
		w11.Y = 182;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 660;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
