
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.MonoNaCl
{
	public partial class MonoNaClGlobalOptions
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Entry NACL_SDK_ROOT;
		private global::Gtk.Button NACL_SDK_ROOT_BrowseButton;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Entry NACL_MONO_ROOT;
		private global::Gtk.Button NACL_MONO_ROOT_BrowseButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.MonoNaCl.MonoNaClGlobalOptions
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.MonoNaCl.MonoNaClGlobalOptions";
			// Container child MonoDevelop.MonoNaCl.MonoNaClGlobalOptions.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.NACL_SDK_ROOT = new global::Gtk.Entry ();
			this.NACL_SDK_ROOT.WidthRequest = 370;
			this.NACL_SDK_ROOT.CanFocus = true;
			this.NACL_SDK_ROOT.Name = "NACL_SDK_ROOT";
			this.NACL_SDK_ROOT.IsEditable = true;
			this.NACL_SDK_ROOT.InvisibleChar = '●';
			this.fixed1.Add (this.NACL_SDK_ROOT);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NACL_SDK_ROOT]));
			w1.X = 10;
			w1.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.NACL_SDK_ROOT_BrowseButton = new global::Gtk.Button ();
			this.NACL_SDK_ROOT_BrowseButton.CanFocus = true;
			this.NACL_SDK_ROOT_BrowseButton.Name = "NACL_SDK_ROOT_BrowseButton";
			this.NACL_SDK_ROOT_BrowseButton.UseUnderline = true;
			this.NACL_SDK_ROOT_BrowseButton.Label = global::Mono.Unix.Catalog.GetString ("Browse");
			this.fixed1.Add (this.NACL_SDK_ROOT_BrowseButton);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NACL_SDK_ROOT_BrowseButton]));
			w2.X = 390;
			w2.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("NaCl SDK root directory:");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w3.X = 10;
			w3.Y = 10;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("NaCl-Mono SDK root directory:");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w4.X = 10;
			w4.Y = 70;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.NACL_MONO_ROOT = new global::Gtk.Entry ();
			this.NACL_MONO_ROOT.WidthRequest = 370;
			this.NACL_MONO_ROOT.CanFocus = true;
			this.NACL_MONO_ROOT.Name = "NACL_MONO_ROOT";
			this.NACL_MONO_ROOT.IsEditable = true;
			this.NACL_MONO_ROOT.InvisibleChar = '●';
			this.fixed1.Add (this.NACL_MONO_ROOT);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NACL_MONO_ROOT]));
			w5.X = 10;
			w5.Y = 90;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.NACL_MONO_ROOT_BrowseButton = new global::Gtk.Button ();
			this.NACL_MONO_ROOT_BrowseButton.CanFocus = true;
			this.NACL_MONO_ROOT_BrowseButton.Name = "NACL_MONO_ROOT_BrowseButton";
			this.NACL_MONO_ROOT_BrowseButton.UseUnderline = true;
			this.NACL_MONO_ROOT_BrowseButton.Label = global::Mono.Unix.Catalog.GetString ("Browse");
			this.fixed1.Add (this.NACL_MONO_ROOT_BrowseButton);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NACL_MONO_ROOT_BrowseButton]));
			w6.X = 390;
			w6.Y = 90;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
