
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.MonoNaCl
{
	public partial class MonoNaClProjectOptions
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.CheckButton requiresGLES;
		private global::Gtk.CheckButton generateManifest;
		private global::Gtk.CheckButton copyAllJsonObjects;
		private global::Gtk.CheckButton copyAllHtmlObjects;
		private global::Gtk.Label label1;
		private global::Gtk.Entry appName;
		private global::Gtk.Label label2;
		private global::Gtk.Entry appVersion;
		private global::Gtk.Entry appDescription;
		private global::Gtk.Label label4;
		private global::Gtk.CheckButton copyAllJSObjects;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.MonoNaCl.MonoNaClProjectOptions
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.MonoNaCl.MonoNaClProjectOptions";
			// Container child MonoDevelop.MonoNaCl.MonoNaClProjectOptions.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.requiresGLES = new global::Gtk.CheckButton ();
			this.requiresGLES.CanFocus = true;
			this.requiresGLES.Name = "requiresGLES";
			this.requiresGLES.Label = global::Mono.Unix.Catalog.GetString ("Requires GLES");
			this.requiresGLES.DrawIndicator = true;
			this.requiresGLES.UseUnderline = true;
			this.fixed1.Add (this.requiresGLES);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.requiresGLES]));
			w1.X = 10;
			w1.Y = 10;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.generateManifest = new global::Gtk.CheckButton ();
			this.generateManifest.CanFocus = true;
			this.generateManifest.Name = "generateManifest";
			this.generateManifest.Label = global::Mono.Unix.Catalog.GetString ("Generate Manifest");
			this.generateManifest.DrawIndicator = true;
			this.generateManifest.UseUnderline = true;
			this.fixed1.Add (this.generateManifest);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.generateManifest]));
			w2.X = 10;
			w2.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.copyAllJsonObjects = new global::Gtk.CheckButton ();
			this.copyAllJsonObjects.CanFocus = true;
			this.copyAllJsonObjects.Name = "copyAllJsonObjects";
			this.copyAllJsonObjects.Label = global::Mono.Unix.Catalog.GetString ("Copy all JSON objects");
			this.copyAllJsonObjects.DrawIndicator = true;
			this.copyAllJsonObjects.UseUnderline = true;
			this.fixed1.Add (this.copyAllJsonObjects);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.copyAllJsonObjects]));
			w3.X = 10;
			w3.Y = 40;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.copyAllHtmlObjects = new global::Gtk.CheckButton ();
			this.copyAllHtmlObjects.CanFocus = true;
			this.copyAllHtmlObjects.Name = "copyAllHtmlObjects";
			this.copyAllHtmlObjects.Label = global::Mono.Unix.Catalog.GetString ("Copy all HTML objects");
			this.copyAllHtmlObjects.DrawIndicator = true;
			this.copyAllHtmlObjects.UseUnderline = true;
			this.fixed1.Add (this.copyAllHtmlObjects);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.copyAllHtmlObjects]));
			w4.X = 10;
			w4.Y = 70;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("App Name:");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w5.X = 10;
			w5.Y = 140;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.appName = new global::Gtk.Entry ();
			this.appName.WidthRequest = 200;
			this.appName.CanFocus = true;
			this.appName.Name = "appName";
			this.appName.IsEditable = true;
			this.appName.InvisibleChar = '●';
			this.fixed1.Add (this.appName);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.appName]));
			w6.X = 130;
			w6.Y = 135;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("App Version:");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w7.X = 10;
			w7.Y = 180;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.appVersion = new global::Gtk.Entry ();
			this.appVersion.WidthRequest = 200;
			this.appVersion.CanFocus = true;
			this.appVersion.Name = "appVersion";
			this.appVersion.IsEditable = true;
			this.appVersion.InvisibleChar = '●';
			this.fixed1.Add (this.appVersion);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.appVersion]));
			w8.X = 130;
			w8.Y = 175;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.appDescription = new global::Gtk.Entry ();
			this.appDescription.WidthRequest = 200;
			this.appDescription.CanFocus = true;
			this.appDescription.Name = "appDescription";
			this.appDescription.IsEditable = true;
			this.appDescription.InvisibleChar = '●';
			this.fixed1.Add (this.appDescription);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.appDescription]));
			w9.X = 130;
			w9.Y = 215;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("App Description:");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w10.X = 10;
			w10.Y = 220;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.copyAllJSObjects = new global::Gtk.CheckButton ();
			this.copyAllJSObjects.CanFocus = true;
			this.copyAllJSObjects.Name = "copyAllJSObjects";
			this.copyAllJSObjects.Label = global::Mono.Unix.Catalog.GetString ("Copy all JS objects");
			this.copyAllJSObjects.DrawIndicator = true;
			this.copyAllJSObjects.UseUnderline = true;
			this.fixed1.Add (this.copyAllJSObjects);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.copyAllJSObjects]));
			w11.X = 200;
			w11.Y = 70;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
