
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Entry openTextBox;
	private global::Gtk.Entry saveTextBox;
	private global::Gtk.Button convertButton;
	private global::Gtk.Entry rotX;
	private global::Gtk.CheckButton useColorsCheckBox;
	private global::Gtk.CheckButton useUVCheckBox;
	private global::Gtk.CheckButton useNormalCheckBox;
	private global::Gtk.Entry rotY;
	private global::Gtk.Entry rotZ;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Open Path:");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 19;
		w1.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Save Path:");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w2.X = 20;
		w2.Y = 53;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.openTextBox = new global::Gtk.Entry ();
		this.openTextBox.WidthRequest = 500;
		this.openTextBox.CanFocus = true;
		this.openTextBox.Name = "openTextBox";
		this.openTextBox.IsEditable = true;
		this.openTextBox.InvisibleChar = '●';
		this.fixed1.Add (this.openTextBox);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.openTextBox]));
		w3.X = 87;
		w3.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.saveTextBox = new global::Gtk.Entry ();
		this.saveTextBox.WidthRequest = 500;
		this.saveTextBox.CanFocus = true;
		this.saveTextBox.Name = "saveTextBox";
		this.saveTextBox.IsEditable = true;
		this.saveTextBox.InvisibleChar = '●';
		this.fixed1.Add (this.saveTextBox);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.saveTextBox]));
		w4.X = 87;
		w4.Y = 47;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.convertButton = new global::Gtk.Button ();
		this.convertButton.CanFocus = true;
		this.convertButton.Name = "convertButton";
		this.convertButton.UseUnderline = true;
		this.convertButton.Label = global::Mono.Unix.Catalog.GetString ("Convert");
		this.fixed1.Add (this.convertButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.convertButton]));
		w5.X = 84;
		w5.Y = 149;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rotX = new global::Gtk.Entry ();
		this.rotX.CanFocus = true;
		this.rotX.Name = "rotX";
		this.rotX.Text = global::Mono.Unix.Catalog.GetString ("90");
		this.rotX.IsEditable = true;
		this.rotX.InvisibleChar = '●';
		this.fixed1.Add (this.rotX);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.rotX]));
		w6.X = 425;
		w6.Y = 83;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.useColorsCheckBox = new global::Gtk.CheckButton ();
		this.useColorsCheckBox.CanFocus = true;
		this.useColorsCheckBox.Name = "useColorsCheckBox";
		this.useColorsCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Use Colors");
		this.useColorsCheckBox.DrawIndicator = true;
		this.useColorsCheckBox.UseUnderline = true;
		this.fixed1.Add (this.useColorsCheckBox);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.useColorsCheckBox]));
		w7.X = 17;
		w7.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.useUVCheckBox = new global::Gtk.CheckButton ();
		this.useUVCheckBox.CanFocus = true;
		this.useUVCheckBox.Name = "useUVCheckBox";
		this.useUVCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Use UVs");
		this.useUVCheckBox.Active = true;
		this.useUVCheckBox.DrawIndicator = true;
		this.useUVCheckBox.UseUnderline = true;
		this.fixed1.Add (this.useUVCheckBox);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.useUVCheckBox]));
		w8.X = 116;
		w8.Y = 89;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.useNormalCheckBox = new global::Gtk.CheckButton ();
		this.useNormalCheckBox.CanFocus = true;
		this.useNormalCheckBox.Name = "useNormalCheckBox";
		this.useNormalCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Use Normals");
		this.useNormalCheckBox.Active = true;
		this.useNormalCheckBox.DrawIndicator = true;
		this.useNormalCheckBox.UseUnderline = true;
		this.fixed1.Add (this.useNormalCheckBox);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.useNormalCheckBox]));
		w9.X = 197;
		w9.Y = 88;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rotY = new global::Gtk.Entry ();
		this.rotY.CanFocus = true;
		this.rotY.Name = "rotY";
		this.rotY.Text = global::Mono.Unix.Catalog.GetString ("0");
		this.rotY.IsEditable = true;
		this.rotY.InvisibleChar = '●';
		this.fixed1.Add (this.rotY);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.rotY]));
		w10.X = 425;
		w10.Y = 116;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rotZ = new global::Gtk.Entry ();
		this.rotZ.CanFocus = true;
		this.rotZ.Name = "rotZ";
		this.rotZ.Text = global::Mono.Unix.Catalog.GetString ("0");
		this.rotZ.IsEditable = true;
		this.rotZ.InvisibleChar = '●';
		this.fixed1.Add (this.rotZ);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.rotZ]));
		w11.X = 425;
		w11.Y = 148;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Rot X:");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w12.X = 372;
		w12.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Rot Y:");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w13.X = 372;
		w13.Y = 121;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Rot Z:");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w14.X = 374;
		w14.Y = 151;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 614;
		this.DefaultHeight = 226;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
